name: actflow
services:
    actflow-cli:
        container_name: actflow-cli
        environment:
            - PLUGINS=ActFlow.Integrations.Core,1.1.0;ActFlow.Integrations.XML,1.1.0
            - LIMITER=100
            - PORT=5523
        ports:
            - 5523:5523
        image: kris701/actflow-cli
        volumes:
            - actflow-cli-persistent:/opt/ActFlow/.persistent
            - actflow-cli-runners:/opt/ActFlow/.runners
            - actflow-cli-completed:/opt/ActFlow/.completed
            - type: bind
              source: <path to your config>
              target: /opt/ActFlow/actflowconfig.json
        restart: unless-stopped
    actflow-web:
        container_name: actflow-web
        ports: 
          - 5524:8080
        image: kris701/actflow-web
        restart: unless-stopped
volumes:
    actflow-cli-persistent:
        name: actflow-cli-persistent
    actflow-cli-runners:
        name: actflow-cli-runners
    actflow-cli-completed:
        name: actflow-cli-completed