name: Build and Publish

on:
  push:
    branches:
      - main

jobs: 
  publishActFlow:
    runs-on: ubuntu-latest
    name: Publish "ActFlow"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Install dependencies
        run: dotnet restore

      - name: Add nuget source
        run: |
          dotnet nuget add source --username kris701 --password ${{ secrets.API_KEY_GITHUB }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/kris701/index.json"

      - name: Build (Release) and Publish [ActFlow]
        run: |  
          cd ActFlow
          dotnet build --configuration Release
          dotnet pack --configuration Release
          cd bin
          cd Release
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_GITHUB }} --source "github" --skip-duplicate
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_NUGET }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
          cd ../../..

      - name: Build (Release) and Publish [ActFlow.Integrations.Core]
        run: |  
          cd Integrations/Core/ActFlow.Integrations.Core
          dotnet build --configuration Release
          dotnet pack --configuration Release
          cd bin
          cd Release
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_GITHUB }} --source "github" --skip-duplicate
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_NUGET }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
          cd ../../../../..

      - name: Build (Release) and Publish [ActFlow.Integrations.DatabaseSharp]
        run: |  
          cd Integrations/DatabaseSharp/ActFlow.Integrations.DatabaseSharp
          dotnet build --configuration Release
          dotnet pack --configuration Release
          cd bin
          cd Release
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_GITHUB }} --source "github" --skip-duplicate
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_NUGET }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
          cd ../../../../..

      - name: Build (Release) and Publish [ActFlow.Integrations.EMail]
        run: |  
          cd Integrations/EMail/ActFlow.Integrations.EMail
          dotnet build --configuration Release
          dotnet pack --configuration Release
          cd bin
          cd Release
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_GITHUB }} --source "github" --skip-duplicate
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_NUGET }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
          cd ../../../../..

      - name: Build (Release) and Publish [ActFlow.Integrations.JSON]
        run: |  
          cd Integrations/JSON/ActFlow.Integrations.JSON
          dotnet build --configuration Release
          dotnet pack --configuration Release
          cd bin
          cd Release
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_GITHUB }} --source "github" --skip-duplicate
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_NUGET }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
          cd ../../../../..

      - name: Build (Release) and Publish [ActFlow.Integrations.ML.NET]
        run: |  
          cd Integrations/ML.NET/ActFlow.Integrations.ML.NET
          dotnet build --configuration Release
          dotnet pack --configuration Release
          cd bin
          cd Release
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_GITHUB }} --source "github" --skip-duplicate
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_NUGET }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
          cd ../../../../..

      - name: Build (Release) and Publish [ActFlow.Integrations.OpenWebUISharp]
        run: |  
          cd Integrations/OpenWebUISharp/ActFlow.Integrations.OpenWebUISharp
          dotnet build --configuration Release
          dotnet pack --configuration Release
          cd bin
          cd Release
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_GITHUB }} --source "github" --skip-duplicate
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_NUGET }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
          cd ../../../../..

      - name: Build (Release) and Publish [ActFlow.Integrations.XML]
        run: |  
          cd Integrations/XML/ActFlow.Integrations.XML
          dotnet build --configuration Release
          dotnet pack --configuration Release
          cd bin
          cd Release
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_GITHUB }} --source "github" --skip-duplicate
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_NUGET }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
          cd ../../../../..

      - name: Build (Release) and Publish [ActFlow.Integrations.Javascript]
        run: |  
          cd Integrations/Javascript/ActFlow.Integrations.Javascript
          dotnet build --configuration Release
          dotnet pack --configuration Release
          cd bin
          cd Release
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_GITHUB }} --source "github" --skip-duplicate
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_NUGET }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
          cd ../../../../..

      - name: Build (Release) and Publish [ActFlow.Integrations.Time]
        run: |  
          cd Integrations/Time/ActFlow.Integrations.Time
          dotnet build --configuration Release
          dotnet pack --configuration Release
          cd bin
          cd Release
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_GITHUB }} --source "github" --skip-duplicate
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_NUGET }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
          cd ../../../../..

      - name: Build (Release) and Publish [ActFlow.Integrations.SerializableHttps]
        run: |  
          cd Integrations/SerializableHttps/ActFlow.Integrations.SerializableHttps
          dotnet build --configuration Release
          dotnet pack --configuration Release
          cd bin
          cd Release
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_GITHUB }} --source "github" --skip-duplicate
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_NUGET }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
          cd ../../../../..

      - name: Build (Release) and Publish [ActFlow.Integrations.Math]
        run: |  
          cd Integrations/Math/ActFlow.Integrations.Math
          dotnet build --configuration Release
          dotnet pack --configuration Release
          cd bin
          cd Release
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_GITHUB }} --source "github" --skip-duplicate
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_NUGET }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
          cd ../../../../..

      - name: Build (Release) and Publish [ActFlow.CLI]
        run: |  
          cd ActFlow.CLI
          dotnet build --configuration Release
          dotnet pack --configuration Release
          cd bin
          cd Release
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_GITHUB }} --source "github" --skip-duplicate
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_NUGET }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
          cd ../../..

      - name: Build (Release) and Publish [ActFlow.Archive]
        run: |  
          cd ActFlow.Archive
          dotnet build --configuration Release
          dotnet pack --configuration Release
          cd bin
          cd Release
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_GITHUB }} --source "github" --skip-duplicate
          dotnet nuget push "*.nupkg" --api-key ${{ secrets.API_KEY_NUGET }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate
          cd ../../..

  publishActFlowDocker:
    name: Update Docker Images
    needs: publishActFlow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.API_KEY_GITHUB }}

      - name: Get CLI Project version
        id: get-version
        uses: kzrnm/get-net-sdk-project-versions-action@v1
        with:
          proj-path: ./ActFlow.CLI/ActFlow.CLI.csproj

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Docker/.Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/actflow:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/actflow:${{ steps.get-version.outputs.package-version }}
            ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/actflow:latest
            ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/actflow:${{ steps.get-version.outputs.package-version }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/actflow:latest
          cache-to: type=inline,mode=min